[project]
org-name = "ballerina"
version = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "math"
    version = "1.0.0"
    path = "../math-native/build/libs/math-native-1.0.0.jar"
    groupId = "ballerina"
    modules = ["math"]
