[project]
org-name = "ballerina"
version = "1.0.0"

[dependencies]
"ballerina/time" = "1.0.1"
"ballerina/stringutils" = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "crypto"
    version = "1.0.0"
    path = "../crypto-native/build/libs/crypto-native-1.0.0.jar"
    groupId = "ballerina"
    modules = ["crypto"]

    [[platform.libraries]]
    artifactId = "commons-codec"
    version = "1.9"
    path = "./lib/commons-codec-1.9.jar"
    groupId = "commons-codec"
    modules = ["crypto"]
