[project]
org-name = "ballerina"
version = "0.6.8"

[dependencies]
"ballerina/io" = "0.5.0"
"ballerina/log" = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "socket"
    version = "0.6.8"
    path = "../socket-native/build/libs/socket-native-0.6.8.jar"
    groupId = "ballerina"
    modules = ["socket"]

    [[platform.libraries]]
    artifactId = "socket"
    version = "0.6.8"
    path = "../socket-test-utils/build/libs/socket-test-utils-0.6.8.jar"
    groupId = "org.ballerinalang.stdlib.socket"
    modules = ["socket"]
    scope = "testOnly"
