[project]
org-name = "ballerina"
version = "1.0.0"

[dependencies]
"ballerina/cache" = "2.0.0"
"ballerina/crypto" = "1.0.0"
"ballerina/log" = "1.0.0"
"ballerina/config" = "1.0.0"
"ballerina/stringutils" = "0.5.0"
"ballerina/task" = "1.1.0"
"ballerina/time" = "1.0.1"
"ballerina/system" = "0.6.0"
"ballerina/io" = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "auth"
    version = "1.0.0"
    path = "../auth-native/build/libs/auth-native-1.0.0.jar"
    groupId = "ballerina"
    modules = ["auth"]
