name: Draft A Release On Docker Build

on:
    workflow_dispatch:
        inputs:
            version:
                description: Release Version
                required: true
                default: Swan Lake Preview 5
        branches: [ master ]

jobs:
    build_docker: 
        runs-on: ubuntu-latest
        # steps:
        #     - uses: actions/checkout@v2
        #     - uses: actions/setup-node@v1
        #       with:
        #         node-version: 12
        #     - run: npm ci
        #     - run: ./gradlew clean build

        steps:
         -
            name: Checkout
            uses: actions/checkout@v2
         -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
         -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
         -
            name: Login to DockerHub
            uses: docker/login-action@v1 
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
         -
            name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: .
                file: ./resources/Dockerfile
                platforms: linux/amd64,linux/arm64,linux/386
                push: true
                tags: user/app:latest

    test_build:
        needs: build_docker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 12
            - run: npm ci
            - run: ./gradlew clean build

    draft_release:
        needs: test_build
        runs-on: ubuntu-latest

        steps:
            - 
                uses: release-drafter/release-drafter@v5
                with:
                    env:
                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
             